name = input("Enter your name: ")
PRN = int(input("Enter the PRN: "))
amount = float(input("Enter the amount you have paid: "))
isit = bool(input("Is the amount you paid lega? \n"))

print(name)
print(type(name))
print(PRN)
print(type(PRN))
print(amount)
print(type(amount))
print(isit)
print(type(isit))
print(str(PRN))
print(type(PRN))